### ISSUE TITLE
use `node.getPublicKey()` with cobo  Mnemonic but get wrong pubkey

### ISSUE THREAD

**Issue by CaosBad** [cobowallet/eos-wallet#3]
```
const node = HDNode.fromMnemonic('my cobo Mnemonic')
const pubkey = node.getPublicKey()
const privatekey = node.getPrivateKey()

```
try to use BIP39 mnemonic which generate by cobo wallet ,and register a EOS account in the wallet , but I cant use the @cobo/eos tool get the right pubkey.

**Comment by LIU9293** [comment]
https://cobo.com/keypair
 Use this tool.
